trigger:
  branches:
    include:
      - main

pool:
  name: "linux"

variables:
  - group: vault-auth
  - group: aws-role-dataservices
  - group: env-prd

steps:
  - checkout: self

  - task: UseNode@1
    inputs:
      version: "16.x"

  - task: CSGP.csgp-pipelines.auth-vault.VaultAuth@0
    displayName: "Vault - Authentication"

  - script: scripts/install-with-pnpm
    displayName: "install packages"

  - script: pnpm check-all
    displayName: "Static type check, prettier, jest, and linting"

  - script: "pnpm build"
    displayName: "build package"

  - script: "cd ./dist && yarn publish"
    displayName: "publish package"
