# Let the trigger be the branch policy
trigger: none
pool:
  name: "linux"

steps:
  - checkout: self

  - task: UseNode@1
    inputs:
      version: "16.x"

  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      version: "6.x"

  - script: scripts/install-with-pnpm
    displayName: "install packages"

  - script: pnpm check-all
    displayName: "Static type check, prettier, jest, and linting"

  - script: pnpm run-test
    displayName: "Generate a test C# file"

  - script: cd ./tmp/TestNamespace && dotnet build
    displayName: "Dotnet build"

  - script: "pnpm build"
    displayName: "ensure build works"
